version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: halaldb
      POSTGRES_USER: halal
      POSTGRES_PASSWORD: halal
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/halaldb
      SPRING_DATASOURCE_USERNAME: halal
      SPRING_DATASOURCE_PASSWORD: halal

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  pgdata:
